### ISSUE TITLE
sim65 test: should it work perfectly?

### ISSUE THREAD

**Issue by sidneycadot** [bbbradsmith/6502vdelay#2]
Hi guys,

Nice work -- I've been toying with this problem for a few days and got it down to be correct for 34 delay cycles and up, but your latest solution is better by an impressive margin!

I am trying to reproduce the tests you're running with sim65 but I see quite a bit of deviations from the expected behavior. So my first question is: is this test still up-to-date and does it pass on your side?

 I do my work on Linux so I essentially reworked the batch-file you provide, as well as the Python script ("test.py"), to be able to run tests in parallel, bringing the runtime for all cases from 0 to 65,535  down to 10 seconds on my system.
 
 Here's what I see (raw cycle counts as returned by sim65, not corrected for the 'null' case):
 
[entire range 0..65535](https://data.jigsaw.nl/vdelay_large.png)
[cases 0..1000]( https://data.jigsaw.nl/vdelay_small.png)

I am pretty much convinced your vdelay implementation is correct, since I ran it in my own test setup (using a real Atari 8-bit machine). So I suspect either sim65 is not cycle-accurate, or I am making a mistake somewhere.

**Comment by bbbradsmith** [comment]
Just now I recompiled with the current windows snapshot, and there has been no change to the results. There should not be spikes at regular intervals like that, you should have an output showing only 3 points of change:

Output:
```
----- NULL: 1447
    0 0000: 29
    1 0001: 0
   30 001E: 1
count: 65536
```

I'm not aware of any deficiency in sim6502 but if there is one and you can identify it, it would be helpful to improve the cc65 project. (Maybe there's some uninitialized variable that manifests a problem on linux only?)

The vdelay correctness I have personally tested on NES and Apple II hardware and accurate emulators, but not as rigorously as the sim6502 test.

As for speeding up the tests with parallelism or other methods, I never considered it necessary. If working on a delay algorithm, if it's going to fail it's most likely to fail very early on. You don't really need to run the 65536 test until you already know you're passing e.g. up to 1000. So, even though the full test takes a few minutes, in practice it only really needs to be run as a final check before publishing an update.

**Comment by bbbradsmith** [comment]
For additional reference, here is the test.bin generated by the current windows snapshot. You should compare this against your test.bin also to see that there wasn't a difference in the compilation toolchain either.
[test.zip](https://github.com/bbbradsmith/6502vdelay/files/11860665/test.zip)

**Comment by sidneycadot** [comment]
Thanks! I reproduce your result and found the error in my Python script: I specified the 4-digit hex argument to the test program using small letters a-f rather than capital letters A-F, which means the cycle counts were not parsed correctly -- oops. With that changed, I reproduce the behavior perfectly.

The parallelization is indeed not a super valuable improvement, but in Python it's quite literally a 2-line change to make that work.

I am tantalizingly close to shaving off another cycle of the vdelay routine. If I get that working I'll let you know; at least now I'll be able to run exhaustive tests.

Thanks,

  Sidney

**Comment by bbbradsmith** [comment]
Ah, is it really that easy to get parallelism? I'm curious what the change looks like. :)

**Comment by sidneycadot** [comment]
Hi,

You can find my version of the script here: https://github.com/sidneycadot/6502vdelay-fork/blob/master/test/run_tests.py

The big difference is that it doesn't create a script and parse an output file, instead calling out to sim65 directly and collecting the results itself. This has the added bonus that it is platform independent.

By writing a sim65 run as a function (well, a method inside a class to capture some configuration variables), it becomes possible to use the multiprocessing.Pool, and in particular its 'map' method, to implement parallellization essentially for free. It's a pretty neat way of getting those extra cores to do something useful.

Note that I made a fork of your repo, in preparation for (hopefully) making pull requests if/when I find any vdelay improvements, although I suspect it's already pretty close to optimal. At some point I intend to remove it again.

**Comment by sidneycadot** [comment]
Closing the issue, my mistake.
