### ISSUE TITLE
Shrinking 'vdelay' routine by 9 bytes

### ISSUE THREAD

**Issue by sidneycadot** [bbbradsmith/6502vdelay#3]
Hi,

I found a way to make the vdelay routine smaller by 9 bytes while keeping it functionally identical, see:

https://github.com/sidneycadot/6502vdelay-fork/blob/master/vdelay.s
  
The trick is to enter a loop that decrements AX in accordance with the cyles taken to traverse the loop, until X becomes zero. This can be written a lot shorter than the previous method of burning 256 cycles per traversal in a dex loop.

Perhaps this method could be an inspiration to decrease the size of the vdelay_full path even further (it is now 13 bytes, down from 22 in your current version).

I could turn this into a pull request but I don't quite understand your convention for commenting cycle counts. Perhaps it's best to copy the new version from the link given above, and comment it in your own convention? I am fine with either; please let me know.

**Comment by bbbradsmith** [comment]
A pull request is fine. I can amend the formatting when I have time to review it.

**Comment by sidneycadot** [comment]
Ok will do. Would you also be interested in a pull request for my cleaned-up and parallelized test runner and correspionding Makefile? This allows people like me to run the test on linux, and it also improves the test in Windows.

**Comment by sidneycadot** [comment]
I'll just make the pull request for the test runner, too. You can always reject it :)

**Comment by bbbradsmith** [comment]
PR #4 and #5 have been merged now.
