### ISSUE TITLE
Cycle timings comment incorrect on line 39 of vdelay_small

### ISSUE THREAD

**Issue by gfoot** [bbbradsmith/6502vdelay#6]
The comment on line 39 says this:

`@5: BRPAGE bcs, @6  ;  2 3 2 3 2  7F 7F 00 00 00`

However it should say this:

`@5: BRPAGE bcs, @6  ;  2 3 2 3 3  7F 7F 00 00 00`

Note the fifth cycle count should be 3 rather than 2.  Apologies I don't have time to correct this myself.

Edit: Line 46 has an error too, it should be "- 3 2 2" not "-3 2 3":

`    BRPAGE beq, @0  ;  - 3 2 3  -- 00 01 02`

Thanks for sharing the code!

**Comment by bbbradsmith** [comment]
Amended, thank you.
